title: StackStats
description: Crypto Portfolio Tracker
theme: minima
baseurl: "/stackstats"
url: "https://rhinak.github.io"

# Build settings
markdown: kramdown

# Permalink structure for clean URLs
permalink: pretty

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
